name: CI

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  cypress-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cypress-io/github-action@v2
      with:
        start: npm run start:prod
        wait-on: 'http://localhost:3000'
        
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: cypress-screenshots
        path: cypress/screenshots
  
  api-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1

    - name: Install Dependencies
      run: npm ci
      
    - name: Run Jest and SuperTest
      run: |
        npm run test:jest
        npm run test:supertest
        
  visual-test:
    needs: [cypress-test, api-test]
    runs-on: ubuntu-latest
    steps:
    - name: Check test status
      if: ${{ needs.cypress-test.result != 'success' || needs.api-test.result != 'success' }} 
      run: exit 1
