name: CI-Tests

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  cypress-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cypress-io/github-action@v6
      with:
        working-directory: client
        build: npm run build
        start: npm run start
        browser: chrome
        
    # - uses: actions/upload-artifact@v2
    #   if: failure()
    #   with:
    #     name: cypress-screenshots
    #     path: cypress/screenshots
  
  api-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies and Test
      run: cd server && npm ci && npm test
        
  # visual-test:
  #   needs: [cypress-test, api-test]
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Check test status
  #     if: ${{ needs.cypress-test.result != 'success' || needs.api-test.result != 'success' }} 
  #     run: exit 1
