name: Frontend Tests
'on':
  push:
    branches:
      - main
    paths:
      - 'client/**'

jobs:

  cypress-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cypress-io/github-action@v6
      with:
        working-directory: client
        build: npm run build
        start: npm run start
        browser: chrome
